// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// This script doesn't have serial test for platform that doesn't support serial port
//

PRINT ****RUNNING ALL ULOGGER UNIT TESTS****
PRINT
PRINT CLIENT API UNIT TESTS
RUN_SCRIPT z:\testdata\scripts\te_client.script
PRINT SERVER UNIT TESTS
RUN_SCRIPT z:\testdata\scripts\te_server.script
PRINT SYSTEM CONFIG TESTS
RUN_SCRIPT z:\testdata\scripts\te_sysconfig.script
PRINT FILE PLUG-IN TESTS
RUN_SCRIPT z:\testdata\scripts\te_file.script
PRINT **completed all ULogger Unit Tests** 
PRINT SERIAL PLUG-IN TESTS
RUN_SCRIPT z:\testdata\scripts\te_outfrwk.script
PRINT SYSTEM STARTER TESTS
RUN_SCRIPT z:\testdata\scripts\te_sysstart.script
PRINT
PRINT ****COMPLETED ALL ULOGGER UNIT TESTS EXCEPT FOR CLT****