// Copyright (c) 2007-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName               	uloggerv1-file-unit-test-suite.script
//! @SYMScriptTestEnvironment       	TEF



PRINT ----------------------------------------------------------
PRINT   Test te_file.mmp
PRINT ----------------------------------------------------------
LOAD_SUITE uloggerplugfiletest


START_TESTCASE			DT-DEBUG-TRACE-UTFv1-ULoggerPlugFile-0001
//! @SYMTestCaseID		DT-DEBUG-TRACE-UTFv1-ULoggerPlugFile-0001
//! @SYMTestCaseDesc     Run test for file plugin 
//! @SYMTestPriority     Critical
//! @SYMTestActions    Set and configure file plugin 
//! @SYMTestExpectedResults      error returns as expected
//! @SYMTestType         UT
//! @SYMTestStatus   Implemented
//! @SYMPREQ                 PREQ1635
//! @SYMREQ 
RUN_TEST_STEP 100 uloggerplugfiletest file0Step
END_TESTCASE			DT-DEBUG-TRACE-UTFv1-ULoggerPlugFile-0001
