// Copyright (c) 2007-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName               	uloggerv1-sysstart-unit-test-suite.script
//! @SYMScriptTestEnvironment       	TEF



PRINT ----------------------------------------------------------
PRINT   Test te_sysstart.mmp
PRINT ----------------------------------------------------------
LOAD_SUITE uloggersysstarttest


START_TESTCASE			DT-DEBUG-TRACE-UTFv1-UloggerSysStart-0001
//! @SYMTestCaseID		DT-DEBUG-TRACE-UTFv1-UloggerSysStart-0001
//! @SYMTestCaseDesc     Test systarter methods for ulogger
//! @SYMTestPriority     Critical
//! @SYMTestActions    Call available start/configuration methods for ulogger systart
//! @SYMTestExpectedResults      error returns as expected
//! @SYMTestType         UT
//! @SYMTestStatus   Implemented
//! @SYMPREQ                 PREQ1635
//! @SYMREQ
RUN_TEST_STEP 100 uloggersysstarttest sysStart0Step
END_TESTCASE			DT-DEBUG-TRACE-UTFv1-UloggerSysStart-0001
