//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0001

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0001

//! @SYMTestCaseDesc          Script 2: Test authentication, paspphrase caching, etc

//!                           

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           0. Initialisation

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           

//!                           First we delete the keystore data file, so that we know we are setting the

//!                           passphrase with our first key add operation.

//!                           Then we set up some keys for the rest of the test script to use:

//!                           

//!                           Key:     Type:

//!                           banana	RSA

//!                           mango	DSA

//!                           tomato	DH

//!                           

//!                           test passphrase timeout affects all keys, and all processes

//! @SYMTestActions           1) 0.1, Delete keystore data file

//!                           2) 0.2, Opening key store in manager mode

//!                           3) 0.3 Delete everything

RUN_TEST_STEP                 -1    CTestHandler        deletekeystoredata  

RUN_TEST_STEP                 -1    CTestHandler        init                   authobjects.ini	SEC-FILETOKENS-AUTHOBJECTS_V2-0001-002

RUN_TEST_STEP                 -1    CTestHandler        deletekeys          

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0001





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0002

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0002

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           1. Test passphrase caching

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           

//!                           1.1 Test adding a key leaves it open and with default timeout of 30 seconds

//! @SYMTestActions           1) 1.1.1, Add key banana

//!                           2) 1.1.2, Get timeout, expect default of 30 seconds

//!                           3) 1.1.3, Get time remaining, expect 30 seconds

//!                           4) 1.1.4, Sign, don't expect passphrase prompt

//!                           5) 1.1.5, Add key mango

//!                           6) 1.1.6, Add key tomato

//!                           7) 1.1.7, Check everything added ok

//!                           8) 1.1.8, Set passphrase timeout to "don't cache"

RUN_TEST_STEP                 -1    CTestHandler        addkey                 authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-001

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-002

RUN_TEST_STEP                 -1    CTestHandler        timeremaining          authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-003

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-004

RUN_TEST_STEP                 -1    CTestHandler        addkey                 authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-005

RUN_TEST_STEP                 -1    CTestHandler        addkey                 authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-006

RUN_TEST_STEP                 -1    CTestHandler        listkeys               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-007

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0002-008

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0002





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0003

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0003

//! @SYMTestCaseDesc          1.2 Test getting and setting the timeout works

//!                           

//!                           1.2.1 Test setting timeout via keystore

//! @SYMTestActions           1) 1.2.1.1, Set passphrase timeout to 5 seconds via keystore

//!                           2) 1.2.1.2, Get timeout on banana, expect 5 seconds

//!                           3) 1.2.1.3, Get timeout on mango, expect 5 seconds

//!                           4) 1.2.1.4, Get timeout on tomato, expect 5 seconds

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0003-001

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0003-002

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0003-003

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0003-004

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0003





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0004

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0004

//! @SYMTestCaseDesc          1.2.2 Test setting timeout via auth object

//! @SYMTestActions           1) 1.2.2.1, Set passphrase timeout to 10 seconds via auth object

//!                           2) 1.2.2.3, Get timeout on banana, expect 10 seconds

//!                           3) 1.2.2.4, Get timeout on mango, expect 10 seconds

//!                           4) 1.2.1.5, Get timeout on tomato, expect 10 seconds

RUN_TEST_STEP                 -1    CTestHandler        authsettimeout         authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0004-001

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0004-002

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0004-003

RUN_TEST_STEP                 -1    CTestHandler        gettimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0004-004

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0004





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0005

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0005

//! @SYMTestCaseDesc          1.3 Test cached passphrases expire and that we can get the time remaining

//! @SYMTestActions           1) 1.3.1, Get time remaining, expect 0 cos no passphrase cached

//!                           2) 1.3.2, Sign, expect passphrase prompt

//!                           3) 1.3.3, Get time remaining

//!                           4) 1.3.4, Wait 5 seconds

//!                           5) 1.3.5, Get time remaining, expect 5 seconds

//!                           6) 1.3.6, Sign, don't expect passphrase prompt

//!                           7) 1.3.7, Wait another 5 seconds

//!                           8) 1.3.8, Get time remaining, expect 0 again

//!                           9) 1.3.9, Sign, expect passphrase prompt

RUN_TEST_STEP                 -1    CTestHandler        timeremaining          authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-001

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-002

RUN_TEST_STEP                 -1    CTestHandler        timeremaining          authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-003

RUN_TEST_STEP                 -1    CTestHandler        sleep                  authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-004

RUN_TEST_STEP                 -1    CTestHandler        timeremaining          authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-005

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-006

RUN_TEST_STEP                 -1    CTestHandler        sleep                  authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-007

RUN_TEST_STEP                 -1    CTestHandler        timeremaining          authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-008

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0005-009

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0005





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0006

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0006

//! @SYMTestCaseDesc          1.4 Test auth object open and close

//! @SYMTestActions           1) 1.4.1.1, Close object

//!                           2) 1.4.1.2, Sign, expect passphrase prompt

//!                           3) 1.4.1.3, Sign again, don't expect passphrase prompt

//!                           4) 1.4.1.4, Close object

//!                           5) 1.4.1.5, Open banana

//!                           6) 1.4.1.6, Sign again, don't expect passphrase prompt

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-001

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-002

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-003

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-004

RUN_TEST_STEP                 -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-005

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0006-006

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0006





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0007

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0007

//! @SYMTestCaseDesc          1.4.2 Test that opening/closing a key opens/closes keys all keys we can use

//! @SYMTestActions           1) 1.4.2.1, Open mango, don't expect passphrase prompt

//!                           2) 1.4.2.2, Close object

//!                           3) 1.4.2.3, Open mango, expect passphrase prompt

//!                           4) 1.4.2.4, Close object again

RUN_TEST_STEP                 -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0007-001

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0007-002

RUN_TEST_STEP                 -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0007-003

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0007-004

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0007





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0008

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0008

//! @SYMTestCaseDesc          1.4.3 Test that the user gets three attempts to enter the passphrase

//! @SYMTestActions           1) 1.4.3.1, Open banana with wrong passphrase, test that we get only three attempts

//!                           2) 1.4.3.2, Open banana, get passphrase right on second attempt

//!                           3) 1.4.3.3, Close banana

//!                           4) 1.4.3.4, Open banana, get passphrase right on last attempt

RUN_TEST_STEP !Error=-11000   -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0008-001

RUN_TEST_STEP                 -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0008-002

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0008-003

RUN_TEST_STEP                 -1    CTestHandler        authopen               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0008-004

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0008





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0009

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0009

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           2. Test list protected objects

//!                           //////////////////////////////////////////////////////////////////////////////

//! @SYMTestActions           1) 2.1, List protected objects for banana

//!                           2) 2.2, List protected objects for mango

//!                           3) 2.3, List protected objects for tomato

RUN_TEST_STEP                 -1    CTestHandler        listprotectedobjects   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0009-001

RUN_TEST_STEP                 -1    CTestHandler        listprotectedobjects   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0009-002

RUN_TEST_STEP                 -1    CTestHandler        listprotectedobjects   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0009-003

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0009





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0010

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0010

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           3. Test changing the passphrase

//!                           //////////////////////////////////////////////////////////////////////////////

//! @SYMTestActions           1) 3.1, Set passphrase timeout to 30 seconds

//!                           2) 3.2, Sign with banana, cache passphrase

//!                           3) 3.3.1, Attempt to change the passphrase, but supply wrong current passphrase

//!                           4) 3.3.2, Sign with the key, expect passphrase still cached

//!                           5) 3.4, Change the passphrase

//!                           6) 3.5, Sign but supply the old passphrase, expect failure

//!                           7) 3.6, Sign with correct passphrase

//!                           8) 3.7, Set passphrase timeout back to "don't cache"

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-001

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-002

RUN_TEST_STEP !Error=-11000   -1    CTestHandler        changepassphrase       authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-003

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-004

RUN_TEST_STEP                 -1    CTestHandler        changepassphrase       authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-005

RUN_TEST_STEP !Error=-11000   -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-006

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-007

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0010-008

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0010





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0011

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0011

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           4. Test unblocking the passphrase

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           5. Test relocking the store

//!                           //////////////////////////////////////////////////////////////////////////////

//! @SYMTestActions           1) 5.1.1, Opening second unified key store

//!                           2) 5.1.2, Set passphrase timeout to 30 seconds

//!                           3) 5.2, Sign, expect passphrase prompt

//!                           4) 5.3, Close object via 2nd key store

//!                           5) 5.4, Sign, don't expect passphrase prompt

//!                           6) 5.5, Relock store via 2nd key store

//!                           7) 5.6, Sign, expect passphrase prompt

//!                           8) 5.7.1, Close key store 2

//!                           9) 5.7.2, Set passphrase timeout back to "don't cache"

RUN_TEST_STEP                 -1    CTestHandler        init                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-001

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-002

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-003

RUN_TEST_STEP                 -1    CTestHandler        authclose              authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-004

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-005

RUN_TEST_STEP                 -1    CTestHandler        relockstore            authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-006

RUN_TEST_STEP                 -1    CTestHandler        sign                   authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-007

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        settimeout             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0011-009

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0011





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0012

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0012

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           6. Test security policies

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           

//!                           6.1 Test default policy is to police based on SID of the creator

//! @SYMTestActions           1) 6.1.1, Get default use policy

//!                           2) 6.1.2, Get default management policy

RUN_TEST_STEP                 -1    CTestHandler        getusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0012-001

RUN_TEST_STEP                 -1    CTestHandler        getmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0012-002

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0012





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0013

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0013

//! @SYMTestCaseDesc          6.2 Test setting policies for the keys

//! @SYMTestActions           1) 6.2.1, Set banana's use policy based on SID and capabilities

//!                           2) 6.2.2, Check banana's use policy set correctly

//!                           3) 6.2.3, Set mango's use policy based on VID and capabilities

//!                           4) 6.2.4, Check mango's use policy set correctly

//!                           5) 6.2.5, Set tomato's use policy based on just capabilities

//!                           6) 6.2.6, Check tomato's use policy set correctly

//!                           7) 6.2.7.1, Test we can't set management policy that doesn't include the calling process

//!                           8) 6.2.7.2, Test we can't set management policy that doesn't include the calling process

//!                           9) 6.2.7.3, Test we can't set management policy that doesn't include the calling process

//!                           10) 6.2.7.4, Set banana's management policy based on just capabilities

//!                           11) 6.2.8, Check banana's management policy set correctly

//!                           12) 6.2.9, Set mango's management policy based on SID and capabilities

//!                           13) 6.2.10, Check mango's management policy set correctly

//!                           14) 6.2.11, Set tomato's management policy based on VID and capabilities

//!                           15) 6.2.12, Check tomato's management policy set correctly

RUN_TEST_STEP                 -1    CTestHandler        setusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-001

RUN_TEST_STEP                 -1    CTestHandler        getusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-002

RUN_TEST_STEP                 -1    CTestHandler        setusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-003

RUN_TEST_STEP                 -1    CTestHandler        getusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-004

RUN_TEST_STEP                 -1    CTestHandler        setusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-005

RUN_TEST_STEP                 -1    CTestHandler        getusepolicy           authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-006

RUN_TEST_STEP !Error=-6       -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-007

RUN_TEST_STEP !Error=-6       -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-008

RUN_TEST_STEP !Error=-6       -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-009

RUN_TEST_STEP                 -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-010

RUN_TEST_STEP                 -1    CTestHandler        getmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-011

RUN_TEST_STEP                 -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-012

RUN_TEST_STEP                 -1    CTestHandler        getmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-013

RUN_TEST_STEP                 -1    CTestHandler        setmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-014

RUN_TEST_STEP                 -1    CTestHandler        getmanagementpolicy    authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0013-015

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0013





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0014

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0014

//! @SYMTestCaseDesc          6.3 Test enforcement of security policies

//! @SYMTestActions           1) 6.3.1, Test use policy enforcement for SID and capabilities

//!                           2) 6.3.2, Test use policy enforcement for VID and capabilities

//!                           3) 6.3.3, Test use policy enforcement for just capabilities

//!                           4) 6.3.4, Test banana's management policy enforcement (just capabilities)

//!                           5) 6.3.5, Test mango's management policy enforcement (SID and capabilities)

//!                           6) 6.3.6, Test tomato's management policy enforcement (VID and capabilities)

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-001

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-002

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-003

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-004

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-005

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0014-006

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0014





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0015

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0015

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           7. Test policing of other APIs

//!                           //////////////////////////////////////////////////////////////////////////////

//!                           

//!                           7.1 Test set timeout is policed with WriteDeviceData capability

//! @SYMTestActions           1) 7.1, Test policing of set timeout

//!                           2) 7.2, Test policing of create and import by WriteUserData

//!                           3) 7.3, Test policing of list by ReadUserData

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0015-001

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0015-002

RUN_TEST_STEP                 -1    CTestHandler        policytest             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0015-003

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0015





START_TESTCASE                SEC-FILETOKENS-AUTHOBJECTS_V2-0016

//! @SYMTestCaseID            SEC-FILETOKENS-AUTHOBJECTS_V2-0016

//! @SYMTestCaseDesc          //////////////////////////////////////////////////////////////////////////////

//!                           Cleanup

//!                           //////////////////////////////////////////////////////////////////////////////

//! @SYMTestActions           1) 8.0, List keys

//!                           2) 8.1, Delete keys

//!                           3) 8.2, Close key store

//!                           4) 8.3, Sleep 5 seconds

//!                           5) 8.4, Check for server heap error

RUN_TEST_STEP                 -1    CTestHandler        listkeys               authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0016-001

RUN_TEST_STEP                 -1    CTestHandler        deletekeys             authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0016-002

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        sleep                  authobjects.ini   SEC-FILETOKENS-AUTHOBJECTS_V2-0016-004

RUN_TEST_STEP                 -1    CTestHandler        checkserverheaperror

END_TESTCASE                  SEC-FILETOKENS-AUTHOBJECTS_V2-0016





