//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//


START_TESTCASE               SEC-FILETOKENS-TESTNEWKEYSTORE-1-0001

//! @SYMTestCaseID           SEC-FILETOKENS-TESTNEWKEYSTORE-1-0001

//! @SYMTestCaseDesc     
     
//!					////////////////////////////////////////////////////////////////////////////////////
//!					//	Operations on migrated key store
//!					////////////////////////////////////////////////////////////////////////////////////

//! @SYMTestActions           1) Opening key store in manager mode

//!                           2) List all keys

//!                           3) Open a DH key

//!                           4) derive for dhkey

//!                           5) Sign with RSA key

//!                           6) Decrypt with RSA key

//!                           7) Closing key store

//!                           8) Closing key store

//!                           9) Sleep 5 seconds

//!                          10) Check for server heap error


RUN_TEST_STEP -1 CTestHandler init testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-001

RUN_TEST_STEP -1 CTestHandler listallkeys testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-002

RUN_TEST_STEP -1 CTestHandler open testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-003

RUN_TEST_STEP -1 CTestHandler derive testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-004

RUN_TEST_STEP -1 CTestHandler sign testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-005

RUN_TEST_STEP -1 CTestHandler decrypt testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-006

RUN_TEST_STEP -1 CTestHandler sign testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-007

RUN_TEST_STEP -1 CTestHandler delete

RUN_TEST_STEP -1 CTestHandler sleep testnewkeystore.ini SEC-FILETOKENS-TESTNEWKEYSTORE-1-009

RUN_TEST_STEP -1 CTestHandler checkserverheaperror


END_TESTCASE                SEC-FILETOKENS-TESTNEWKEYSTORE-1-0001


