//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-TKEYSTORE_AUTHENTICATION1-0001

//! @SYMTestCaseID            SEC-TKEYSTORE_AUTHENTICATION1-0001

//! @SYMTestCaseDesc          

//! @SYMTestActions           1) Delete keystore data file

//!                           2) Retrieving label of a particular key store

//!                           3) Closing key store

//!                           4) Retrieving label of a particular key store

//!                           5) Closing key store

//!                           6) 1.0.0.0.1,Opening key store 1 in manager mode - deprecated

//!                           7) 1.0.0.0.2,Opening key store 2 in manager mode

//!                           8) 1.0.0.1.0,Add a key (TEST ID: GT0140-KEY002 and GT0140-KEY003)

//!                           9) 1.0.0.51.1, Get it again

//!                           10) Set a new authentication policy for a key with which the user is not registered

//!                           11) Gets authentication policy for a key

//!                           12) 1.0.0.51.1, Get it again

//!                           13) 1.0.0.1.1,List all keys (TEST ID: INC103084-KEY001)

//!                           14) 1.0.0.1.0.0,export a DH key

//!                           15) 1.1.0 Import a RSA key

//!                           16) 1.1.5 Export a RSA key

//!                           17) Set a new authentication policy for a key with which the user is not registered

//!                           18) 1.1.5 Export a RSA key

//!                           19) 1.12.0.14 Import a PKCS5 encrypted RSA key previously exported with ECipher3DES_CBC

//!                           20) 1.1.0.24 List RSA keys (TEST ID: GT0140-KEY001)

//!                           21) 1.2.0.69.0 Closing key store 1 - deprecated

//!                           22) 1.2.0.69.1 Closing key store 2

//!                           23) 1.4.999.2, Sleep 5 seconds

//!                           24) 1.4.999.3, Check for server heap error

RUN_TEST_STEP                 -1    CTestHandler        deletekeystoredata  

RUN_TEST_STEP                 -1    CTestHandler        init                   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-002

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP !Error=-2       -1    CTestHandler        init                   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-004

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        init                   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-007

RUN_TEST_STEP                 -1    CTestHandler        addkey                 tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-008

RUN_TEST_STEP                 -1    CTestHandler        getkeyinfo             tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-009

RUN_TEST_STEP                 -1    CTestHandler        authenticationpolicy   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-010

RUN_TEST_STEP                 -1    CTestHandler        authenticationpolicy   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-011

RUN_TEST_STEP                 -1    CTestHandler        getkeyinfo             tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-012

RUN_TEST_STEP                 -1    CTestHandler        listallkeys            tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-013

RUN_TEST_STEP !Error=-5       -1    CTestHandler        exportkey              tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-014

RUN_TEST_STEP                 -1    CTestHandler        importkey              tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-015

RUN_TEST_STEP                 -1    CTestHandler        exportkey              tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-016

RUN_TEST_STEP                 -1    CTestHandler        authenticationpolicy   tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-017

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        exportkey              tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-018

RUN_TEST_STEP                 -1    CTestHandler        importkey              tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-019

RUN_TEST_STEP                 -1    CTestHandler        listkeys               tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-020

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        sleep                  tkeystore_authentication1.ini   SEC-TKEYSTORE_AUTHENTICATION1-0001-023

RUN_TEST_STEP                 -1    CTestHandler        checkserverheaperror

END_TESTCASE                  SEC-TKEYSTORE_AUTHENTICATION1-0001





