//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-TKEYSTORE_NOUSERREGISTERED-0001

//! @SYMTestCaseID            SEC-TKEYSTORE_NOUSERREGISTERED-0001

//! @SYMTestCaseDesc          

//! @SYMTestActions           1) Delete keystore data file

//!                           2) Retrieving label of a particular key store

//!                           3) Closing key store

//!                           4) 1.0.0.0.1,Opening key store 1 in manager mode

//!                           5) 1.0.0.0.2,Opening key store 2 in manager mode

//!                           6) 1.0.0.1.0,Add a key (TEST ID: GT0140-KEY002 and GT0140-KEY003)

//!                           7) Delete key (TEST ID: GT0140KEY004)

//!                           8) 1.0.0.51.1, Get it again

//!                           9) Set a new authentication policy for a key with which the user is not registered

//!                           10) Gets authentication policy for a key

//!                           11) 1.0.0.1.1,List all keys (TEST ID: INC103084-KEY001)

//!                           12) 1.1.0 Import a RSA key

//!                           13) 1.1.0 Import a RSA key

//!                           14) 6.2.1, Set cheeku's use policy based on SID and capabilities

//!                           15) 6.2.7.4, Set cheeku's management policy based on just capabilities

//!                           16) 1.1.5 Export a RSA key

//!                           17) 1.1.5 Export a RSA key

//!                           18) 1.2.0.69.0 Closing key store 1

//!                           19) 1.2.0.69.1 Closing key store 2

//!                           20) 1.4.999.2, Sleep 5 seconds

//!                           21) 1.4.999.3, Check for server heap error

RUN_TEST_STEP                 -1    CTestHandler        deletekeystoredata  

RUN_TEST_STEP !Error=-2       -1    CTestHandler        init                   tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-002

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        init                   tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-004

RUN_TEST_STEP                 -1    CTestHandler        init                   tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-005

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        addkey                 tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-006

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        deletekeys             tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-007

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        getkeyinfo             tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-008

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        authenticationpolicy   tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-009

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        authenticationpolicy   tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-010

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        listallkeys            tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-011

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        importkey              tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-012

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        importkey              tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-013

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        setusepolicy           tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-014

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        setmanagementpolicy    tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-015

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        exportkey              tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-016

RUN_TEST_STEP !Error=-11012   -1    CTestHandler        exportkey              tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-017

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        delete              

RUN_TEST_STEP                 -1    CTestHandler        sleep                  tkeystore_nouserregistered.ini   SEC-TKEYSTORE_NOUSERREGISTERED-0001-020

RUN_TEST_STEP                 -1    CTestHandler        checkserverheaperror

END_TESTCASE                  SEC-TKEYSTORE_NOUSERREGISTERED-0001





