// Copyright (c) 2007-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName           te_perf_default.script
//! @SYMScriptTestEnvironment   TEF

RUN_SCRIPT z:\testdata\scripts\te_perf_sanity.script
RUN_SCRIPT z:\testdata\scripts\te_perf_sanity_enabled.script
RUN_SCRIPT z:\testdata\scripts\te_perf_sanity_disabled.script
RUN_SCRIPT z:\testdata\scripts\te_perf_outputcsvsanity.script
