// Copyright (c) 2007-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName           te_perf_guidelines.script
//! @SYMScriptTestEnvironment   TEF


RUN_SCRIPT z:\testdata\scripts\te_perf_guidelines_enabled.script
RUN_SCRIPT z:\testdata\scripts\te_perf_guidelines_disabled.script


LOAD_SUITE te_ostv2integsuite_enabled

PRINT Reset TraceControl config file

START_TEST_BLOCK    20000       te_ostv2integsuite_enabled              \testdata\configs\te_perf_guidelines.ini
    CREATE_OBJECT               DefaultTraceControlConfig               DefaultTraceControlConfig
    COMMAND                     DefaultTraceControlConfig               doTest
END_TEST_BLOCK

PRINT End of Notification API performance tests.
