//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE tupsdb

//! @file
//! @SYMTestCaseID SEC-UPS-DB-DECISIONDATABASEPERFORMANCETESTS-0001
//! @SYMTestCaseDesc Measure the performance of UPS decision database
//! @SYMTestPriority High
//! @SYMTestActions Measure database creation,lookup,insertion and deletion times
//! @SYMTestExpectedResults The test completes with KErrNone completion code.
//! @SYMREQ PerformanceRequirements

START_TESTCASE SEC-UPS-DB-DECISIONDATABASEPERFORMANCETESTS-0001

RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_1
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_2
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_3
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_4
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_5
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_6
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_7
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_8
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_9
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_10
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_11
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_12
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_13
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_14
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_15
RUN_TEST_STEP 100 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_16
RUN_TEST_STEP 200 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_17
RUN_TEST_STEP 200 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_18
RUN_TEST_STEP 200 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_19
RUN_TEST_STEP 200 tupsdb MeasurePerformance z:\tups\tupsdb\scripts\tupsdbperformance.ini performance_test_20

END_TESTCASE SEC-UPS-DB-DECISIONDATABASEPERFORMANCETESTS-0001
