<!-- Symbian HTTP Doxygen document footer -->
		<HR>
		<CENTER>
			Author :&nbsp;
			<A HREF="mailto:HTTP_Project_Team@symbian.com">The HTTP Team</A>, &nbsp;
			<ADDRESS><SMALL>
			API documentation auto-generated by <a HREF="http://www.doxygen.org">Doxygen</A> from the latest commented source.
			</SMALL></ADDRESS>
			<ADDRESS><SMALL>
				Copyright &copy; 2000-2001 
				<a href="http://www.symbian.com/">Symbian Ltd.</a>
				 All rights reserved.
			</SMALL></ADDRESS>
		</CENTER>
		<P ALIGN="RIGHT">
		<a HREF="http://web.intra/Dev/SysDoc/DeveloperLibrary/Quartz6.0/Product/Quartz6.0/index.html">
		<IMG  BORDER="0" SRC="symbianlogo.jpg">
		</a></P>
	</BODY>
</HTML>