//
// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// 

PRINT Run All t_shapetestserver tests
//
LOAD_SUITE t_shapetestserver
RUN_TEST_STEP 200 t_shapetestserver Hindi
RUN_TEST_STEP 200 t_shapetestserver Kannada
RUN_TEST_STEP 200 t_shapetestserver Gujarati
RUN_TEST_STEP 200 t_shapetestserver Bengali
RUN_TEST_STEP 200 t_shapetestserver Tamil
RUN_TEST_STEP 200 t_shapetestserver Telugu
RUN_TEST_STEP 200 t_shapetestserver Gurmukhi
RUN_TEST_STEP 200 t_shapetestserver Malayalam