// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all ulibz_test
LOAD_SUITE ulibz 

CONSECUTIVE

START_TESTCASE SYSLIB-EZLIB2-UT-4035
//!@SYMTestCaseID 			SYSLIB-EZLIB2-UT-4035
RUN_TEST_STEP !Result=0 5 ulibz libzcomp_decomp
END_TESTCASE SYSLIB-EZLIB2-UT-4035

START_TESTCASE SYSLIB-EZLIB2-UT-4099
//!@SYMTestCaseID 			SYSLIB-EZLIB2-UT-4099
RUN_TEST_STEP !Result=0 5 ulibz libzdefl_Infl
END_TESTCASE SYSLIB-EZLIB2-UT-4099

START_TESTCASE SYSLIB-EZLIB2-UT-4172
//!@SYMTestCaseID 			SYSLIB-EZLIB2-UT-4172
RUN_TEST_STEP !Result=0 5 ulibz libzgzio
END_TESTCASE SYSLIB-EZLIB2-UT-4172

START_TESTCASE SYSLIB-EZLIB2-UT-4183
//!@SYMTestCaseID 			SYSLIB-EZLIB2-UT-4183
RUN_TEST_STEP !Result=0 5 ulibz libzversion
END_TESTCASE SYSLIB-EZLIB2-UT-4183
