@rem
@rem Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
@rem All rights reserved.
@rem This component and the accompanying materials are made available
@rem under the terms of "Eclipse Public License v1.0"
@rem which accompanies this distribution, and is available
@rem at the URL "http://www.eclipse.org/legal/epl-v10.html".
@rem
@rem Initial Contributors:
@rem Nokia Corporation - initial contribution.
@rem
@rem Contributors:
@rem
@rem Description:
@rem

T_PLUGINDISCOVERY.EXE
T_CAPCHECK.EXE
T_ECOMCANCEL.EXE
T_RESOLVER.EXE
T_ROMRESOLVER.EXE
T_ROMONLY.EXE
T_LISTIMPLEMENTATION.EXE
T_DEFAULTRESOLVER.EXE
T_LOADMANAGER.EXE
T_SUICIDE.EXE
T_DISCOVERER.EXE
T_REGISTRAR.EXE
T_REGISTRYDATA.EXE
T_BACKUPNOTIFIER.EXE
T_FINALCLOSE.EXE
T_PLUGINUPGRADE.EXE
T_DRIVEMOUNT.EXE
T_ECOMDEFECT.EXE
t_rogueplugin.exe
T_SERVERSTARTUPMGR.EXE
T_ECOMSSAENABLED.EXE
T_ECOMSSADISABLED.EXE
T_ECOMENTRY.EXE
COMPONENTINFOTEST.EXE
ECOMTESTS.EXE
ECOMSERVERTEST.EXE
DEFAULTLOGOUTPUTTEST.EXE
DATALOGGERTEST.EXE
TRANSITIONTEST.EXE
TESTCONTROLLERTEST.EXE
TESTMANAGERTEST.EXE
COMPONENTTESTERTEST.EXE
UNITTESTTEST.EXE
T_PLATSECTEST.EXE
T_VALIDATEREGISTRY.EXE
T_DOWNGRADE.EXE
T_DRIVEINFO.EXE
T_DISABLEDRIVES.EXE
T_IMPLEMENTATIONINFORMATION.EXE
T_LANGUAGE.EXE
T_HASHCHECK.EXE
T_ECOMSWI.EXE
T_ECOMBUR.EXE
T_ExtendedInterfaces.EXE
T_RESOLVERPERF.EXE
T_RESOLVERCACHE.EXE
T_HEAPTEST.EXE
t_ecomeikerrortest.exe
