// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all ttrapsignal
LOAD_SUITE ttrapsignal

CONSECUTIVE
START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 125 ttrapsignal  Testcustomsignalapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testcustomsigsetapi1 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testcustomsigsetapi2 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0013

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0016

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0017

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0018
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0018
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0018

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0019
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0019
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0019

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0020
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0020
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustombsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0020

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0021
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0021
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testcustomsigactionapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0021

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0022
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0022
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0022

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0023
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0023
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0023

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0024
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0024
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0024

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0025
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0025
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0025

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0026
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0026
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegcustomsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0026

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0027
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0027
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 125 ttrapsignal  Testignoresignalapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0027

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0028
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0028
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresignalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0028

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0029
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0029
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresignalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0029

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0030
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0030
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresignalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0030

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0031
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0031
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresignalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0031

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0032
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0032
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresignalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0032

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0033
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0033
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testignoresigsetapi1 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0033

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0034
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0034
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testignoresigsetapi2 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0034

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0035
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0035
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0035

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0036
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0036
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0036

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0037
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0037
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0037

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0038
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0038
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0038

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0039
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0039
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0039

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0040
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0040
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0040

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0041
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0041
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0041

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0042
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0042
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0042

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0043
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0043
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0043

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0044
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0044
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0044

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0045
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0045
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignorebsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0045

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0046
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0046
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testignoresigactionapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0046

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0047
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0047
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0047

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0048
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0048
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0048

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0049
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0049
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0049

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0050
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0050
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0050

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0051
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0051
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegignoresigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0051

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0052
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0052
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigignoreapi \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0052

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0053
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0053
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegsigignoreapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0053

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0054
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0054
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegsigignoreapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0054

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0055
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0055
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegsigignoreapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0055

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0056
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0056
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegsigignoreapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0056

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0057
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0057
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegsigignoreapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0057

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0058
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0058
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0058

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0059
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0059
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0059

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0060
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0060
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0060

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0061
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0061
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0061

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0062
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0062
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsignalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0062

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0063
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0063
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0063

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0064
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0064
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0064

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0065
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0065
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0065

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0066
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0066
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0066

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0067
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0067
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigsetapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0067

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0068
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0068
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultbsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0068

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0069
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0069
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultbsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0069

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0070
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0070
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultbsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0070

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0071
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0071
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultbsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0071

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0072
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0072
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultbsd_signalapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0072

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0073
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0073
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0073

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0074
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0074
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0074

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0075
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0075
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0075

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0076
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0076
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0076

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0077
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0077
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testnegdefaultsigactionapi \tstdapis\ttrapsignal.ini SectionNegsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0077

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0078
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0078
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigsethold1 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0078

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0079
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0079
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi1 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0079

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0080
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0080
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi2 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0080

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0081
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0081
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 660 ttrapsignal  Testsigactionapi3 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0081

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0082
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0082
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi4 \tstdapis\ttrapsignal.ini SectionFlagnotsup1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0082

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0083
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0083
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi4 \tstdapis\ttrapsignal.ini SectionFlagnotsup2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0083

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0084
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0084
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi4 \tstdapis\ttrapsignal.ini SectionFlagnotsup3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0084

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0085
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0085
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi4 \tstdapis\ttrapsignal.ini SectionFlagnotsup4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0085

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0086
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0086
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 ttrapsignal  Testsigactionapi5 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0086

START_TESTCASE  	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0087
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0087
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 125 ttrapsignal  Testsigactionapi6 \tstdapis\ttrapsignal.ini SectionSignalinput
END_TESTCASE  		OPENENV-LIBC-CIT-TESTTRAPSIGNAL-0087




