// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tsemwait
LOAD_SUITE tsemwait

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0001
//! @SYMTestCaseID 	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tsemwait TestSem286
END_TESTCASE  		OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0001

START_TESTCASE  	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0002
//! @SYMTestCaseID 	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tsemwait TestSem287
END_TESTCASE  		OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0002

START_TESTCASE  	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0003
//! @SYMTestCaseID 	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tsemwait TestSem288
END_TESTCASE  		OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0003

START_TESTCASE  	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0004
//! @SYMTestCaseID 	OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tsemwait TestSem290
END_TESTCASE  		OPENENV-LIBPTHREAD-CIT-TESTSEMWAIT-0004


