/*
* Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/


/**
 @internalComponent
*/
#define KScreenFontUidCalc13n   268435493
#define KScreenFontUidCalc18n   268435494
#define KScreenFontUidCalc24n   268435495

#define KFontStoreFileUidEon5   268435509

#define KScreenFontUidAgnsym11  268435559
#define KScreenFontUidAgnsym16n 268435496

#define KScreenFontUidEiksym15  268435661
#define KScreenFontUidCalcinv   268435668

#define KScreenFontUidSquashed  268435701
#define KScreenFontUidDigital35 268435752

/**
@deprecated
The fonts that the following UIDs represent are no longer available for use.
*/
#define KScreenFontUidArialBold8       268435951
#define KScreenFontUidArialBold11      268435952
#define KScreenFontUidArialBold13      268435953
#define KScreenFontUidArialNormal8     268435954
#define KScreenFontUidArialNormal11    268435955
#define KScreenFontUidArialNormal13    268435956
#define KScreenFontUidArialNormal15    268435957
#define KScreenFontUidArialNormal18    268435958
#define KScreenFontUidArialNormal22    268435959
#define KScreenFontUidArialNormal27    268435960
#define KScreenFontUidArialNormal32    268435961

#define KScreenFontUidTimesBold8       268435962
#define KScreenFontUidTimesBold11      268435963
#define KScreenFontUidTimesBold13      268435964
#define KScreenFontUidTimesNormal8     268435965
#define KScreenFontUidTimesNormal11    268435966
#define KScreenFontUidTimesNormal13    268435967
#define KScreenFontUidTimesNormal15    268435968
#define KScreenFontUidTimesNormal18    268435969
#define KScreenFontUidTimesNormal22    268435970
#define KScreenFontUidTimesNormal27    268435971
#define KScreenFontUidTimesNormal32    268435972

#define KScreenFontUidCourierBold8     268436062
#define KScreenFontUidCourierBold11    268436063
#define KScreenFontUidCourierBold13    268436064
#define KScreenFontUidCourierNormal8   268436065
#define KScreenFontUidCourierNormal11  268436066
#define KScreenFontUidCourierNormal13  268436067
#define KScreenFontUidCourierNormal15  268436068
#define KScreenFontUidCourierNormal18  268436069
#define KScreenFontUidCourierNormal22  268436070
#define KScreenFontUidCourierNormal27  268436071
#define KScreenFontUidCourierNormal32  268436072

#define KScreenFontUidMon18n    268435497
#define KScreenFontUidMon18b    268435498
#define KScreenFontUidMon9n     268435499
#define KScreenFontUidMon9b     268435500

#define KScreenFontUidTiny1     268435501
#define KScreenFontUidTiny2     268435502
#define KScreenFontUidTiny3     268435503
#define KScreenFontUidTiny4     268435504

