//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

// platsec tests



START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-1

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-1

//! @file                     

//! @SYMTestCaseDesc          Initialise - not a test

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Initialise - not a test

RUN_TEST_STEP                 -1    CTestHandler        InitManager         

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-1





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-2

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-2

//! @file                     

//! @SYMTestCaseDesc          Clearing existing applications - not a test

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Clearing existing applications - not a test

RUN_TEST_STEP                 -1    CTestHandler        ClearAllApps        

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-2





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-3

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-3

//! @file                     

//! @SYMTestCaseDesc          Add applications - adding five apps with UID 24601, 642828, 12345, 10, 12

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Add applications - adding five apps with UID 24601, 642828, 12345, 10, 12

RUN_TEST_STEP                 -1    CTestHandler        AddApp                 script1.ini   SEC-TCERTAPPS-SCRIPT1-3-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-3





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-4

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-4

//! @file                     

//! @SYMTestCaseDesc          Getting the application list

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Getting the application list

RUN_TEST_STEP                 -1    CTestHandler        GetApplications        script1.ini   SEC-TCERTAPPS-SCRIPT1-4-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-4





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-5

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-5

//! @file                     

//! @SYMTestCaseDesc          Destroy the manager

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Destroy the manager

RUN_TEST_STEP                 -1    CTestHandler        DestroyManager      

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-5





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-6

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-6

//! @file                     

//! @SYMTestCaseDesc          Sleep 5 seconds

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Sleep 5 seconds

RUN_TEST_STEP                 -1    CTestHandler        sleep                  script1.ini   SEC-TCERTAPPS-SCRIPT1-6-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-6





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-7

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-7

//! @file                     

//! @SYMTestCaseDesc          Initialise

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Initialise

RUN_TEST_STEP                 -1    CTestHandler        InitManager         

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-7





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-8

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-8

//! @file                     

//! @SYMTestCaseDesc          Getting the application list

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Getting the application list

RUN_TEST_STEP                 -1    CTestHandler        GetApplications        script1.ini   SEC-TCERTAPPS-SCRIPT1-8-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-8





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-9

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-9

//! @file                     

//! @SYMTestCaseDesc          Adding an application with the UID already existing

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrAlreadyExists

//! @SYMTestActions           1) Adding an application with the UID already existing

RUN_TEST_STEP !Error=-11      -1    CTestHandler        AddApp                 script1.ini   SEC-TCERTAPPS-SCRIPT1-9-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-9





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-10

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-10

//! @file                     

//! @SYMTestCaseDesc          Remove application UID 24601

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Remove application UID 24601

RUN_TEST_STEP                 -1    CTestHandler        RemoveApp              script1.ini   SEC-TCERTAPPS-SCRIPT1-10-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-10





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-11

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-11

//! @file                     

//! @SYMTestCaseDesc          Remove app which does not exist UID 24601

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNotFound

//! @SYMTestActions           1) Remove app which does not exist UID 24601

RUN_TEST_STEP !Error=-1       -1    CTestHandler        RemoveApp              script1.ini   SEC-TCERTAPPS-SCRIPT1-11-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-11





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-12

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-12

//! @file                     

//! @SYMTestCaseDesc          Get Count

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Get Count

RUN_TEST_STEP                 -1    CTestHandler        AppCount               script1.ini   SEC-TCERTAPPS-SCRIPT1-12-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-12





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-13

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-13

//! @file                     

//! @SYMTestCaseDesc          Get application 10

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Get application 10

RUN_TEST_STEP                 -1    CTestHandler        GetApp                 script1.ini   SEC-TCERTAPPS-SCRIPT1-13-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-13





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-14

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-14

//! @file                     

//! @SYMTestCaseDesc          Get application which does not exist

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNotFound

//! @SYMTestActions           1) Get application which does not exist

RUN_TEST_STEP !Error=-1       -1    CTestHandler        GetApp                 script1.ini   SEC-TCERTAPPS-SCRIPT1-14-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-14





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-15

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-15

//! @file                     

//! @SYMTestCaseDesc          Getting the application list

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Getting the application list

RUN_TEST_STEP                 -1    CTestHandler        GetApplications        script1.ini   SEC-TCERTAPPS-SCRIPT1-15-001

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-15





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-16

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-16

//! @file                     

//! @SYMTestCaseDesc          Delete applications

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Delete applications

RUN_TEST_STEP                 -1    CTestHandler        ClearAllApps        

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-16





START_TESTCASE                SEC-TCERTAPPS-SCRIPT1-17

//! @SYMTestCaseID            SEC-TCERTAPPS-SCRIPT1-17

//! @file                     

//! @SYMTestCaseDesc          Destroy the manager

//! @SYMREQ                   REQ3466

//! @SYMTestCasePriority      High

//! @SYMTestExpectedResults   KErrNone

//! @SYMTestActions           1) Destroy the manager

RUN_TEST_STEP                 -1    CTestHandler        DestroyManager      

END_TESTCASE                  SEC-TCERTAPPS-SCRIPT1-17





