// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tcomport
LOAD_SUITE tcomport

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTCOMPORT-OE-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTCOMPORT-OE-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tcomport test_printf_COM 
END_TESTCASE  		OPENENV-LIBC-CIT-TESTCOMPORT-OE-0001

//to be run manually
//STARTSTART_TESTCASE  	OPENENV-LIBC-CIT-TESTCOMPORT-OE-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTCOMPORT-OE-0002
//! @SYMTestStatus 	3.Released
//RUN_TEST_STEP !Result=0 10 tcomport test_scanf_COM 
//END_TESTCASE  		OPENENV-LIBC-CIT-TESTCOMPORT-OE-0002


