//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
PRINT Run all tsetjmp
LOAD_SUITE tsetjmp

CONSECUTIVE

START_TESTCASE               OE-FUNC-STDLIB-SJMP-0001
RUN_TEST_STEP 1000 tsetjmp setjmpTest \tstdapis\tsetjmp.ini OE-FUNC-STDLIB-SJMP-0001
END_TESTCASE                  OE-FUNC-STDLIB-SJMP-0001

START_TESTCASE                OE-FUNC-STDLIB-SJMP-0002
RUN_TEST_STEP 1000 tsetjmp setjmpTest \tstdapis\tsetjmp.ini OE-FUNC-STDLIB-SJMP-0002
END_TESTCASE                  OE-FUNC-STDLIB-SJMP-0002

START_TESTCASE                OE-FUNC-STDLIB-SJMP-0003
RUN_TEST_STEP 1000 tsetjmp setjmpTest \tstdapis\tsetjmp.ini OE-FUNC-STDLIB-SJMP-0003
END_TESTCASE                  OE-FUNC-STDLIB-SJMP-0003

START_TESTCASE                OE-FUNC-STDLIB-SJMP-0004
RUN_TEST_STEP 1000 tsetjmp setjmpTest \tstdapis\tsetjmp.ini OE-FUNC-STDLIB-SJMP-0004
END_TESTCASE                  OE-FUNC-STDLIB-SJMP-0004

