# Security Policy Plug-in, named properties string table
stringtable SecurityPolicyPluginStrings
#
# Standard token values, enumerations or parameters
#
ESequenceNumberMode _snm
EKeyRefreshRate _krr
ESharedSecret _ss
ERecordLengthUsage _rlu
EAnonymousAllowed _aa
#
# Values for sequence number mode
ENotUsed _nu 
EImplicit _im
EExplicit _ex
#
# Values for 'record length usage' ('not used' value is taken from above)
EUsed _u
#
# Values for 'anonymous allowed'
EAllowed _allowed
ENotAllowed _na
