// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

CONSECUTIVE

START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0001
PRINT --------  Testing utimes ,Capability set to None
RUN_PROGRAM -1 setcap.exe tsystimecap.exe 000000  tsystime_cap1.exe
LOAD_SUITE tsystime_cap1
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP   !Result=13 tsystime_cap1 utimessys
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0001




START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0002
PRINT --------  Testing utimes ,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tsystimecap.exe 000800  tsystime_cap2.exe
LOAD_SUITE tsystime_cap2
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tsystime_cap2 utimessys
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0002



START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0003
PRINT --------  Testing utimes ,Capability set to None
RUN_PROGRAM -1 setcap.exe tsystimecap.exe 000000  tsystime_cap3.exe
LOAD_SUITE tsystime_cap3
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tsystime_cap3 utimesprivate
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0003


START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0004
PRINT --------  Testing utimes,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tsystimecap.exe 000800  tsystime_cap4.exe
LOAD_SUITE tsystime_cap4
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tsystime_cap4 utimesprivate
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPSYSTIME-OE-0004




