//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001

//! @SYMTestCaseID            SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001

//! @SYMTestCaseDesc          

//! @SYMTestActions           1) Construction Vector Test #1 -- even number of bytes

//!                           2) Construction Vector Test #2 -- odd number of bytes

//!                           3) Construction Vector Test #3 -- long unsigned string

//!                           4) OOM start

//!                           5) Construction Vector Test #1 -- even number of bytes

//!                           6) Construction Vector Test #2 -- odd number of bytes

//!                           7) Construction Vector Test #3 -- long unsigned string

//!                           8) OOM end

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-001

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-002

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-003

RUN_TEST_STEP                 -1    CTestHandler        startmemfailure     

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-005

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-006

RUN_TEST_STEP                 -1    CTestHandler        ConstructionVector     tconstructiontests.ini   SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001-007

RUN_TEST_STEP                 -1    CTestHandler        stopmemfailure      

END_TESTCASE                  SEC-CRYPTOSPI-TCONSTRUCTIONTESTS-0001





