//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-CRYPTOSPI-TPRIMEGEN-0001

//! @SYMTestCaseID            SEC-CRYPTOSPI-TPRIMEGEN-0001

//! @SYMTestCaseDesc          

//! @SYMTestActions           1) Prime Generation Vector -- 0 (tests the overflow from something less than KLastPrimeSquared to the probablistic prime generation routines

//!                           2) Prime Generation Vector -- 0 (tests the overflow from something less than KLastPrimeSquared to the probablistic prime generation routines

//!                           3) Prime Generation Vector -- 1

//!                           4) Prime Generation Vector -- 2

//!                           5) Prime Generation Vector -- 3

//!                           6) Prime Generation Vector -- 4

//!                           7) Prime Generation Vector -- 5

//!                           8) Prime Generation Vector -- 6

//!                           9) Prime Generation Vector -- 7

//!                           10) Prime Generation Vector -- 8

//!                           11) Prime Generation Vector -- 9

//!                           12) Prime Generation Vector -- 10

//!                           13) Prime Generation Vector -- 11

//!                           14) Prime Generation

//!                           15) OOM start

//!                           16) Prime Generation

//!                           17) OOM end

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-001

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-002

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-003

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-004

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-005

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-006

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-007

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-008

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-009

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-010

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-011

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-012

RUN_TEST_STEP                 -1    CTestHandler        PrimeGenVector         tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-013

RUN_TEST_STEP                 -1    CTestHandler        PrimeGen               tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-014

RUN_TEST_STEP                 -1    CTestHandler        startmemfailure     

RUN_TEST_STEP                 -1    CTestHandler        PrimeGen               tprimegen.ini   SEC-CRYPTOSPI-TPRIMEGEN-0001-016

RUN_TEST_STEP                 -1    CTestHandler        stopmemfailure      

END_TESTCASE                  SEC-CRYPTOSPI-TPRIMEGEN-0001





