// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tstdio
LOAD_SUITE tstdio

CONSECUTIVE

RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess1 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess2 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess3 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess4 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess5 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess6 
RUN_TEST_STEP !Result=0 5 tstdio  TestFileModeAccess7
RUN_TEST_STEP !Result=0 5 tstdio  TestFileGetsPos
RUN_TEST_STEP !Result=0 5 tstdio  TestFileTellReadWrite
RUN_TEST_STEP !Result=0 5 tstdio  TestFileTellSeek
RUN_TEST_STEP !Result=0 5 tstdio  TestFileLargeData
RUN_TEST_STEP !Result=0 5 tstdio  TestFileReadTell
RUN_TEST_STEP !Result=0 5 tstdio  TestFileReadSeekEnd
RUN_TEST_STEP !Result=0 5 tstdio  TestFileWriteSeekEnd
RUN_TEST_STEP !Result=0 5 tstdio  TestFileFlushWriteSeekEnd
RUN_TEST_STEP !Result=0 5 tstdio  TestFileFlushWriteSeek
RUN_TEST_STEP !Result=0 5 tstdio  TestFileFlushSeekCur
RUN_TEST_STEP !Result=0 5 tstdio  TestFileTellSeekCornerCase1
RUN_TEST_STEP !Result=0 5 tstdio  TestFileTellSeekCornerCase2
RUN_TEST_STEP !Result=0 5 tstdio  TestFileSeekTellOnRW1
RUN_TEST_STEP !Result=0 5 tstdio  TestFileSeekTellOnRW2
RUN_TEST_STEP !Result=0 5 tstdio  TestFileSeekTellOnRW3
RUN_TEST_STEP !Result=0 5 tstdio  TestFileSeekTellOnRW4
RUN_TEST_STEP !Result=0 5 tstdio  TestFileWriteTextMode
RUN_TEST_STEP !Result=0 5 tstdio  TestFileWriteBinaryMode