// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tglob 
LOAD_SUITE tglob 

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globappend 
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globbrace 
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globdooffs
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globmark 
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globnocheck 
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globnosort
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTGLOB-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTGLOB-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tglob globtilde
END_TESTCASE  		OPENENV-LIBC-CIT-TESTGLOB-0007

