//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE tupspolicies
PRINT ----------------------------------------------------------
PRINT tupspolicies: 
PRINT User Prompt Service policy library unit test
PRINT ----------------------------------------------------------

// Clean environment. Policy directory on system drive must not exist for the first tests
// to allow us to check that the library works if the path doesn't exist.
RUN_UTILS DELETEFILE		c:\upsrefnotifier.txt

//! @SYMTestCaseID SEC-UPS-NOTIFIER-0001
//! @SYMTestCaseDesc Tests reference, techview notifier
//! @SYMTestPriority High
//! @SYMTestActions Create requests that should display prompts
//! @SYMTestExpectedResults Notifier windows should be displayed with localised text.
//! @SYMDevelopedForRelease Oghma
START_TESTCASE SEC-UPS-NOTIFIER-0001
RUN_TEST_STEP_RESULT 0 100 tupspolicies TEFUnit.CTestPlugins.TestCacheL z:\tups\tpolicies\scripts\tupsnotifier.ini
END_TESTCASE SEC-UPS-NOTIFIER-0001

// Cleanup automated notifier response
RUN_UTILS DELETEFILE		c:\upsrefnotifier.txt
