//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run all Te_CryptoSpi Suite Tests

//
LOAD_SUITE Te_CryptoSpi
//

//Symmetric Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_SymmetricCipherTestCases.script

//Asymmertric Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_ASymmetricCipherTestCases.script

//Hash Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_HashHmacTestCases.script

//Hash Test Cases use the new CreateHashL()
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_hash_test_cases.script

//Mac Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_mac_test_cases.script

//Random Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_RandomTestCases.script

//Key Exchange, Generation, Signer and Verifier Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_MiscellaneousTestCases.script

//Plug-in Load Test Cases
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_pluginloadtestcases.script

//Plug-in Characteristics
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_plugincharstestcases.script

//Plug-in Rule Based Selection
RUN_SCRIPT z:\testdata\tcryptospi\scripts\te_ruleselectiontestcases.script

PRINT Complate_Te_CryptoSpi_Tests
