//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Run all te_ASymmetricCipherTestCases Tests
//

//
LOAD_SUITE Te_CryptoSpi
//
//! @SYMTestCaseID 	SEC-CRYPTOSPI-ASYM-0001
//! @SYMTestCaseDesc	ASymmetricCipherPositiveObjectLoad

START_TESTCASE SEC-CRYPTOSPI-ASYM-0001
RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherPositiveObjectLoadStep c:\testdata\tcryptospi\configs\ASymmetricCipherPositiveObjectLoad.ini Section0001
RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherPositiveObjectLoadStep c:\testdata\tcryptospi\configs\ASymmetricCipherPositiveObjectLoad.ini Section0002
END_TESTCASE SEC-CRYPTOSPI-ASYM-0001

//! @SYMTestCaseID 	SEC-CRYPTOSPI-ASYM-0002
//! @SYMTestCaseDesc	ASymmetricCipherEncryptedDataCheck

//START_TESTCASE SEC-CRYPTOSPI-ASYM-0002
//RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherEncryptedDataCheckStep c:\testdata\tcryptospi\configs\ASymmetricCipherEncryptedDataCheck.ini Section0001
//RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherEncryptedDataCheckStep c:\testdata\tcryptospi\configs\ASymmetricCipherEncryptedDataCheck.ini Section0002
//END_TESTCASE SEC-CRYPTOSPI-ASYM-0002

//! @SYMTestCaseID 	SEC-CRYPTOSPI-ASYM-0003
//! @SYMTestCaseDesc	ASymmetricCipherEncryptDecrypt

START_TESTCASE SEC-CRYPTOSPI-ASYM-0003
RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherEncryptDecryptStep c:\testdata\tcryptospi\configs\ASymmetricCipherEncryptDecrypt.ini Section0001
RUN_TEST_STEP 100 Te_CryptoSpi ASymmetricCipherEncryptDecryptStep c:\testdata\tcryptospi\configs\ASymmetricCipherEncryptDecrypt.ini Section0002
END_TESTCASE SEC-CRYPTOSPI-ASYM-0003


PRINT Complate_te_ASymmetricCipherTestCases_Tests
