//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Run all te_HashHmacTestCases Tests
//

//
LOAD_SUITE Te_CryptoSpi
//

//***************
//HASH TEST CASES
//***************

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0001
//! @SYMTestCaseDesc	HashPositiveObjectLoad

START_TESTCASE SEC-CRYPTOSPI-HASH-0001
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0001

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0002
//! @SYMTestCaseDesc	HashBasicHashOfData

START_TESTCASE SEC-CRYPTOSPI-HASH-0002
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0002

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0003
//! @SYMTestCaseDesc	HashIncrementalHash

START_TESTCASE SEC-CRYPTOSPI-HASH-0003
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0003

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0004
//! @SYMTestCaseDesc	HashIncrementalHashWithReset

START_TESTCASE SEC-CRYPTOSPI-HASH-0004
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0004

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0005
//! @SYMTestCaseDesc	HashIncrementalHashWithCopy

START_TESTCASE SEC-CRYPTOSPI-HASH-0005
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0005

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0006
//! @SYMTestCaseDesc	HashIncrementalHashWithReplicate

START_TESTCASE SEC-CRYPTOSPI-HASH-0006
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0006

//***************
//HMAC TEST CASES
//***************

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0007
//! @SYMTestCaseDesc	HmacPositiveObjectLoad

START_TESTCASE SEC-CRYPTOSPI-HASH-0007
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0007

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0008
//! @SYMTestCaseDesc	HmacBasicHashOfData

//Note: The HMAC tests corresponding to SHA384 and SHA512 will be uncommented once DEF112025 and DEF112027 are fixed
START_TESTCASE SEC-CRYPTOSPI-HASH-0008
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini SHA256
//RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini SHA384
//RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0008

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0009
//! @SYMTestCaseDesc	HmacIncrementalHash

START_TESTCASE SEC-CRYPTOSPI-HASH-0009
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini SHA256
//RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini SHA384
//RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0009

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0010
//! @SYMTestCaseDesc	HmacIncrementalHashWithReset

START_TESTCASE SEC-CRYPTOSPI-HASH-0010
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA256
//RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA384
//RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0010

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0011
//! @SYMTestCaseDesc	HmacIncrementalHashWithCopy

START_TESTCASE SEC-CRYPTOSPI-HASH-0011
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0011

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0012
//! @SYMTestCaseDesc	HmacIncrementalHashWithReplicate

START_TESTCASE SEC-CRYPTOSPI-HASH-0012
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0012

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0013
//! @SYMTestCaseDesc	HmacSetKeyChecking

START_TESTCASE SEC-CRYPTOSPI-HASH-0013
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0013

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0014
//! @SYMTestCaseDesc	HmacSetOperationModeChecking

START_TESTCASE SEC-CRYPTOSPI-HASH-0014
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA512
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidInitialOperationMode
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidSetOperationMode
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidAlgorithm
END_TESTCASE SEC-CRYPTOSPI-HASH-0014

PRINT Complate_te_HashHmacTestCases_Tests
