//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Run all te_Hash_Test_Cases Tests
//

//
LOAD_SUITE Te_CryptoSpi
//

//***************
//HASH TEST CASES
//***************

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0015
//! @SYMTestCaseDesc	HashPositiveLoad

START_TESTCASE SEC-CRYPTOSPI-HASH-0015
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveLoadStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0015

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0016
//! @SYMTestCaseDesc	HashBasicData

START_TESTCASE SEC-CRYPTOSPI-HASH-0016
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicDataStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0016

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0017
//! @SYMTestCaseDesc	HashIncremental

START_TESTCASE SEC-CRYPTOSPI-HASH-0017
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512L
END_TESTCASE SEC-CRYPTOSPI-HASH-0017

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0018
//! @SYMTestCaseDesc	HashIncrementalWithReset

START_TESTCASE SEC-CRYPTOSPI-HASH-0018
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithResetStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512L
END_TESTCASE SEC-CRYPTOSPI-HASH-0018

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0019
//! @SYMTestCaseDesc	HashIncrementalWithCopy

START_TESTCASE SEC-CRYPTOSPI-HASH-0019
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithCopyStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512L
END_TESTCASE SEC-CRYPTOSPI-HASH-0019

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0020
//! @SYMTestCaseDesc	HashIncrementalWithReplicate

START_TESTCASE SEC-CRYPTOSPI-HASH-0020
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD2L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD4L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini MD5L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA1L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA224L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA256L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA384L
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalWithReplicateStep c:\testdata\tcryptospi\configs\hash_test_cases.ini SHA512L
END_TESTCASE SEC-CRYPTOSPI-HASH-0020


PRINT Complete_te_Hash_Test_Cases_Tests
