//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Run all te_HashHmacTestCases Tests
//

//
LOAD_SUITE Te_CryptoSpi
//

//***************
//HASH TEST CASES
//***************

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0021
//! @SYMTestCaseDesc	HashPositiveObjectLoad

START_TESTCASE SEC-CRYPTOSPI-HASH-0021
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HashPositiveObjectLoad.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0021

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0022
//! @SYMTestCaseDesc	HashBasicHashOfData

START_TESTCASE SEC-CRYPTOSPI-HASH-0022
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashBasicHashOfDataStep c:\testdata\tcryptospi\configs\HashBasicHashOfData.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0022

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0023
//! @SYMTestCaseDesc	HashIncrementalHash

START_TESTCASE SEC-CRYPTOSPI-HASH-0023
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashStep c:\testdata\tcryptospi\configs\HashIncrementalHash.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0023

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0024
//! @SYMTestCaseDesc	HashIncrementalHashWithReset

START_TESTCASE SEC-CRYPTOSPI-HASH-0024
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReset.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0024

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0025
//! @SYMTestCaseDesc	HashIncrementalHashWithCopy

START_TESTCASE SEC-CRYPTOSPI-HASH-0025
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithCopy.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0025

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0026
//! @SYMTestCaseDesc	HashIncrementalHashWithReplicate

START_TESTCASE SEC-CRYPTOSPI-HASH-0026
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HashIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HashIncrementalHashWithReplicate.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0026

//***************
//HMAC TEST CASES
//The following few tests regress on the deprecated Hash APIs
//***************

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0027
//! @SYMTestCaseDesc	HmacPositiveObjectLoad

START_TESTCASE SEC-CRYPTOSPI-HASH-0027
RUN_TEST_STEP 100 Te_CryptoSpi HmacPositiveObjectLoadStep c:\testdata\tcryptospi\configs\HmacPositiveObjectLoad.ini MD2
END_TESTCASE SEC-CRYPTOSPI-HASH-0027

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0028
//! @SYMTestCaseDesc	HmacBasicHashOfData

START_TESTCASE SEC-CRYPTOSPI-HASH-0028
RUN_TEST_STEP 100 Te_CryptoSpi HmacBasicHashOfDataStep c:\testdata\tcryptospi\configs\HmacBasicHashOfData.ini MD4
END_TESTCASE SEC-CRYPTOSPI-HASH-0028

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0029
//! @SYMTestCaseDesc	HmacIncrementalHash

START_TESTCASE SEC-CRYPTOSPI-HASH-0029
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashStep c:\testdata\tcryptospi\configs\HmacIncrementalHash.ini MD5
END_TESTCASE SEC-CRYPTOSPI-HASH-0029

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0030
//! @SYMTestCaseDesc	HmacIncrementalHashWithReset

START_TESTCASE SEC-CRYPTOSPI-HASH-0030
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithResetStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReset.ini SHA1
END_TESTCASE SEC-CRYPTOSPI-HASH-0030

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0031
//! @SYMTestCaseDesc	HmacIncrementalHashWithCopy

START_TESTCASE SEC-CRYPTOSPI-HASH-0031
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithCopyStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithCopy.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0031

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0032
//! @SYMTestCaseDesc	HmacIncrementalHashWithReplicate

START_TESTCASE SEC-CRYPTOSPI-HASH-0032
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacIncrementalHashWithReplicateStep c:\testdata\tcryptospi\configs\HmacIncrementalHashWithReplicate.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0032

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0033
//! @SYMTestCaseDesc	HmacSetKeyChecking

START_TESTCASE SEC-CRYPTOSPI-HASH-0033
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetKeyCheckingStep c:\testdata\tcryptospi\configs\HmacSetKeyChecking.ini SHA512
END_TESTCASE SEC-CRYPTOSPI-HASH-0033

//! @SYMTestCaseID 	SEC-CRYPTOSPI-HASH-0034
//! @SYMTestCaseDesc	HmacSetOperationModeChecking

START_TESTCASE SEC-CRYPTOSPI-HASH-0034
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD2
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD4
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini MD5
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA1
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA224
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA256
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA384
RUN_TEST_STEP 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini SHA512
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidInitialOperationMode
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidSetOperationMode
RUN_TEST_STEP !Result=-5 100 Te_CryptoSpi HmacSetOperationModeCheckingStep c:\testdata\tcryptospi\configs\HmacSetOperationModeChecking.ini InvalidAlgorithm
END_TESTCASE SEC-CRYPTOSPI-HASH-0034

PRINT Complate_te_HashHmacTestCases_Tests
