TESTEXECUTE C:/tef_ezlib2/te_PerformanceTests.Script
TESTEXECUTE	C:/tef_ezlib2/te_backwardscompatibilitytests.script
TESTEXECUTE	C:/tef_ezlib2/te_ezlibeziptests_suite.script
TESTEXECUTE	C:/tef_ezlib2/te_manual_backwardscompatibilitytests.script
TESTEXECUTE	C:/tef_ezlib2/te_manual_performancetests.script
TESTEXECUTE	C:/tef_ezlib2/te_zlib_suite.script
TESTEXECUTE	C:/tef_ezlib2/te_zlib.script
TESTEXECUTE	C:/tef_ezlib2/te_zlib_auto.script
TESTEXECUTE	C:/tef_ezlib2/te_zlib_blocks.script
TESTEXECUTE	C:/tef_ezlib2/te_zlib_advanced.script
TESTEXECUTE	C:/tef_ezlib2/te_ulibz_suite.script