//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE tupsinteg_post1

//! @SYMTestCaseID SEC-UPS-INTEG-POST-0002

START_TESTCASE SEC-UPS-INTEG-POST-0002
RUN_TEST_STEP 100 tupsinteg_post1 UPSClientStep z:\tups\integ\scripts\tups_integ.ini check_sample
END_TESTCASE SEC-UPS-INTEG-POST-0002
