// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tifioctls
LOAD_SUITE tifioctls

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls ExampleL \tstdapis\tifioctls.ini SectionExampleL 
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_2
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_3
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls ListInterfaces \tstdapis\tifioctls.ini SectionListInterfaces_4
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameIndex
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestIfIndexToName \tstdapis\tifioctls.ini SectionTestIfIndexToName_2
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameToIndex \tstdapis\tifioctls.ini SectionTestIfNameToIndex_1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestSiocGIfIndex \tstdapis\tifioctls.ini SectionTestSiocGIfIndex
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0012


START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls TestIfNameToIndex \tstdapis\tifioctls.ini SectionTestIfNameToIndex_2
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0017

// To cover CTtyDesc::IoctlCompletion in backend
START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0018
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0018
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tifioctls ioctltest
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0018

// To cover CTtyDesc::MapCodeAndEcho in backend this would be a manual test
//as we cannot make a key press input for cttydesc console(stdout)
START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0019
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0019
//! @SYMTestStatus 	3.Released
//RUN_TEST_STEP !Result=0 10 tifioctls readtest
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0019

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0020
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0020
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls Testioctlfile
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0020

START_TESTCASE  	OPENENV-LIBC-CIT-TIFIOCTLS-0021
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TIFIOCTLS-0021
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 50 tifioctls Testioctl1
END_TESTCASE  		OPENENV-LIBC-CIT-TIFIOCTLS-0021

