@rem
@rem Copyright (c) 2009-2010 Nokia Corporation and/or its subsidiary(-ies).
@rem All rights reserved.
@rem This component and the accompanying materials are made available
@rem under the terms of "Eclipse Public License v1.0"
@rem which accompanies this distribution, and is available
@rem at the URL "http://www.eclipse.org/legal/epl-v10.html".
@rem
@rem Initial Contributors:
@rem Nokia Corporation - initial contribution.
@rem
@rem Contributors:
@rem
@rem Description:
@rem

t_storset
t_storcrypt
t_storcorupt
t_storfbuf
t_storfdir
t_storfperm
t_storfrecl
t_storfcomp
t_storfserr
t_storfstrm
t_storoom
t_stormemstrm
t_storpage
t_stordelim
t_stordictfs
t_storembed
t_storshape
t_stordict
t_storstrm
t_storverify
t_storconv
t_storucmp
t_storstreamperf
t_storiter
T_storbench
t_stortoc
t_storswizzle
