// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tmiscsignal
LOAD_SUITE tmiscsignal

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testpsignal1 \tstdapis\tmiscsignal.ini Sectionpsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testpsignal1 \tstdapis\tmiscsignal.ini Sectionpsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testpsignal1 \tstdapis\tmiscsignal.ini Sectionpsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testpsignal2 \tstdapis\tmiscsignal.ini Sectionpsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testpsignal2 \tstdapis\tmiscsignal.ini Sectionpsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 20 tmiscsignal  Testcombinesignal1 \tstdapis\tmiscsignal.ini Sectioncombinesignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 20 tmiscsignal  Testcombinesignal1 \tstdapis\tmiscsignal.ini Sectioncombinesignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 20 tmiscsignal  Testcombinesignal2 \tstdapis\tmiscsignal.ini Sectioncombinesignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 20 tmiscsignal  Testcombinesignal2 \tstdapis\tmiscsignal.ini Sectioncombinesignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 20 tmiscsignal  Testcombinesignal3 \tstdapis\tmiscsignal.ini Sectioncombinesignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testsigchildsignal
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmiscsignal  Testsigpipesignal
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tmiscsignal  Testinheritsignal \tstdapis\tmiscsignal.ini Sectioninheritsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0013

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tmiscsignal  Testsigalrmsignal1 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tmiscsignal  Testsigalrmsignal1 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0016

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0017

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0018
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0018
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0018

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0019
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0019
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal6
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0019

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0020
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0020
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal7
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0020

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0021
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0021
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal8
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0021

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0022
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0022
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal2 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal9
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0022

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0023
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0023
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0023

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0024
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0024
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal4 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal10
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0024

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0025
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0025
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal4 \tstdapis\tmiscsignal.ini Sectionsigalarmsignal11
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0025

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0026
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMISCSIGNAL-0026
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 12 tmiscsignal  Testsigalrmsignal5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMISCSIGNAL-0026

