// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all Performance Tests
LOAD_SUITE Te_EZlibEZip

RUN_UTILS MkDir c:\test\
RUN_UTILS MkDir c:\test\ezlibeziptest_data\
RUN_UTILS CopyFile e:\BigSize.doc 			c:\test\ezlibeziptest_data\BigSize.doc

START_TESTCASE SYSLIB-EZLIB2-CT-4303-0001
//!@SYMTestCaseID 			SYSLIB-EZLIB2-CT-4303-0001
	RUN_TEST_STEP !Result=Pass 500 Te_EZlibEZip TestDeflatePerformanceL \tef_ezlib2\te_manual_performancetests.ini Section_TestDeflatePerformanceL_01
END_TESTCASE SYSLIB-EZLIB2-CT-4303-0001

//RUN_UTILS DeleteFile C:\test\ezlibeziptest_data\ptest_BigSize1.zip
RUN_UTILS DeleteDirectory C:\test\ezlibeziptest_data

RUN_UTILS MkDir c:\test\
RUN_UTILS MkDir c:\test\ezlibeziptest_data\
RUN_UTILS CopyFile e:\BigSize.doc 			c:\test\ezlibeziptest_data\BigSize.doc

START_TESTCASE SYSLIB-EZLIB2-CT-4304-0001
//!@SYMTestCaseID 			SYSLIB-EZLIB2-CT-4304-0001
	RUN_TEST_STEP !Result=Pass 500 Te_EZlibEZip TestInflatePerformanceL \tef_ezlib2\te_manual_performancetests.ini Section_TestInflatePerformanceL_01
END_TESTCASE SYSLIB-EZLIB2-CT-4304-0001

//RUN_UTILS DeleteFile C:\test\ezlibeziptest_data\ptest_BigSize1.doc
RUN_UTILS DeleteDirectory C:\test\ezlibeziptest_data

RUN_UTILS MkDir c:\test\
RUN_UTILS MkDir c:\test\ezlibeziptest_data\
RUN_UTILS CopyFile e:\BigSize.doc 			c:\test\ezlibeziptest_data\BigSize.doc

START_TESTCASE SYSLIB-EZLIB2-CT-4305-0001
//!@SYMTestCaseID 			SYSLIB-EZLIB2-CT-4305-0001
	RUN_TEST_STEP !Result=Pass 500 Te_EZlibEZip TestGZipDeflatePerformanceL \tef_ezlib2\te_manual_performancetests.ini Section_TestGZipDeflatePerformanceL_01
END_TESTCASE SYSLIB-EZLIB2-CT-4305-0001

//RUN_UTILS DeleteFile C:\test\ezlibeziptest_data\ptest_BigSize1.gz
RUN_UTILS DeleteDirectory C:\test\ezlibeziptest_data

RUN_UTILS MkDir c:\test\
RUN_UTILS MkDir c:\test\ezlibeziptest_data\
RUN_UTILS CopyFile e:\BigSize.doc 			c:\test\ezlibeziptest_data\BigSize.doc

START_TESTCASE SYSLIB-EZLIB2-CT-4306-0001
//!@SYMTestCaseID 			SYSLIB-EZLIB2-CT-4306-0001
	RUN_TEST_STEP !Result=Pass 500 Te_EZlibEZip TestGZipInflatePerformanceL \tef_ezlib2\te_manual_performancetests.ini Section_TestGZipInflatePerformanceL_01
END_TESTCASE SYSLIB-EZLIB2-CT-4306-0001

//RUN_UTILS DeleteFile C:\test\ezlibeziptest_data\ptest_BigSize1.doc
RUN_UTILS DeleteDirectory C:\test\ezlibeziptest_data

RUN_UTILS MkDir c:\test\
RUN_UTILS MkDir c:\test\ezlibeziptest_data\
RUN_UTILS CopyFile e:\ZipArchive1.zip 			c:\test\ezlibeziptest_data\ZipArchive1.zip


START_TESTCASE SYSLIB-EZLIB2-CT-4307-0001
//!@SYMTestCaseID 			SYSLIB-EZLIB2-CT-4307-0001
	RUN_TEST_STEP !Result=Pass 500 Te_EZlibEZip TestZipArchiveDecompressPerformanceL \tef_ezlib2\te_manual_performancetests.ini Section_TestZipArchiveDecompressPerformanceL_01
END_TESTCASE SYSLIB-EZLIB2-CT-4307-0001

RUN_UTILS DeleteDirectory C:\test\ezlibeziptest_data
