// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
//! @SYMTestSuiteName		SYSLIB-SCHSVR-TE_FLOATING_SCHEDULESUITE
//! @SYMScriptTestEnvironment 	this script can be run in Textshell or Techview.

PRINT Run all te_floating_schedule Suite Tests

//
LOAD_SUITE te_floating_scheduleSuite
//

START_TESTCASE  SYSLIB-SCHSVR-CIT-0277
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0277
//!@SYMTestCaseDesc 		Persistant schedule - Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite persist_hometimeStep
END_TESTCASE  SYSLIB-SCHSVR-CIT-0277

START_TESTCASE   SYSLIB-SCHSVR-CIT-0280
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0280
//!@SYMTestCaseDesc 		Persistant schedule float - Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it floats
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite persist_hometime_floatStep
END_TESTCASE    SYSLIB-SCHSVR-CIT-0280

START_TESTCASE   SYSLIB-SCHSVR-CIT-0278
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0278
//!@SYMTestCaseDesc 		Persistant schedule - UTC
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite persist_utcStep
END_TESTCASE    SYSLIB-SCHSVR-CIT-0278

START_TESTCASE   SYSLIB-SCHSVR-CIT-0279
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0279
//!@SYMTestCaseDesc 		Persistant schedule - UTC & Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite persist_mixedStep
END_TESTCASE    SYSLIB-SCHSVR-CIT-0279

START_TESTCASE   SYSLIB-SCHSVR-CIT-0281
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0281
//!@SYMTestCaseDesc 		Transient schedule - Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite transient_hometimeStep
END_TESTCASE  SYSLIB-SCHSVR-CIT-0281

START_TESTCASE   SYSLIB-SCHSVR-CIT-0284
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0284
//!@SYMTestCaseDesc 		Transient schedule float - Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it floats
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite transient_hometime_floatStep
END_TESTCASE  SYSLIB-SCHSVR-CIT-0284


START_TESTCASE   SYSLIB-SCHSVR-CIT-0282
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0282
//!@SYMTestCaseDesc 		Transient schedule - UTC
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite transient_utcStep
END_TESTCASE  SYSLIB-SCHSVR-CIT-0282

START_TESTCASE   SYSLIB-SCHSVR-CIT-0283
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0283
//!@SYMTestCaseDesc 		Transient schedule - Hometime & UTC
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it fires
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite transient_mixedStep
END_TESTCASE   SYSLIB-SCHSVR-CIT-0283

START_TESTCASE   SYSLIB-SCHSVR-CIT-0285
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-0285
//!@SYMTestCaseDesc 		Transient schedule float offset +1Hr - Hometime
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it floats when scheduled in a timezone that's not GMT
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMPREQ			PREQ234
RUN_TEST_STEP -1 te_floating_scheduleSuite hometime_floatStep
END_TESTCASE  SYSLIB-SCHSVR-CIT-0285

START_TESTCASE   SYSLIB-SCHSVR-CIT-1368
//!@SYMTestCaseID		SYSLIB-SCHSVR-CIT-1368
//!@SYMTestCaseDesc 		DEF061595 - Schedule timers incorrectly expire when system time is changed
//!@SYMTestPriority 		High
//!@SYMTestActions  		For time and condition based test schedule task and check it floats when scheduled in a timezone that's not GMT, check also that the schedule fires correctly when it is enabled before the time and offset is changed
//!@SYMTestExpectedResults	The test must not fail.
//!@SYMDEF			DEF061595
RUN_TEST_STEP -1 te_floating_scheduleSuite DEF061595_Step
END_TESTCASE    SYSLIB-SCHSVR-CIT-1368

PRINT Complete_te_floating_schedule_Tests
