// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// @file
// 
//

PRINT SchSvr TEF Tests

RUN_SCRIPT  C:\TEF_SchSvr\TEF_SSA_ScheduleSuite.script
RUN_SCRIPT  C:\TEF_SchSvr\te_floating_scheduleSuite.script
RUN_SCRIPT  C:\TEF_SchSvr\tef_schsvr_bursuite.script
