// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all twaitsignal
LOAD_SUITE twaitsignal

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testpendingsignal1 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testpendingsignal2 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 600 twaitsignal  Testpendingsignal3 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testpendingsignal4
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0004


START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal1 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 425 twaitsignal  Testwaitsignal2 \tstdapis\twaitsignal.ini SectionNRTnRTsignal1
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 425 twaitsignal  Testwaitsignal2 \tstdapis\twaitsignal.ini SectionNRTnRTsignal2
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 425 twaitsignal  Testwaitsignal2 \tstdapis\twaitsignal.ini SectionNRTnRTsignal3
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 155 twaitsignal  Testwaitsignal3 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal4 
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 155 twaitsignal  Testwaitsignal5 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal6 \tstdapis\twaitsignal.ini SectionNeg_Sigwait1
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal6 \tstdapis\twaitsignal.ini SectionNeg_Sigwait2
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0013

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal7
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal8 \tstdapis\twaitsignal.ini SectionSignalNum1 
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 twaitsignal  Testwaitsignal8 \tstdapis\twaitsignal.ini SectionSignalNum2
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0016

START_TESTCASE  	OPENENV-LIBC-CIT-TWAITSIGNAL-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TWAITSIGNAL-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 60 twaitsignal  Testwaitsignal9 \tstdapis\twaitsignal.ini SectionSignalNum
END_TESTCASE  		OPENENV-LIBC-CIT-TWAITSIGNAL-0017

