//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE                SEC-CERTMAN-TX509_DEV_CERTS-0001

//! @SYMTestCaseID            SEC-CERTMAN-TX509_DEV_CERTS-0001

//! @SYMTestCaseDesc          

//! @SYMTestActions           1) TX509 Extension Tests 01 - Empty certificate extensions

//!                           2) TX509 Extension Tests 02 - Missing Device Id constraint

//!                           3) TX509 Extension Tests 03 - Missing SID constraint

//!                           4) TX509 Extension Tests 04 - Missing VID constraint

//!                           5) TX509 Extension Tests 05 - Missing capabilities constraint

//!                           6) TX509 Extension Tests 06 - Match All Fields

//!                           7) TX509 Extension Tests 07 - Multiple Values

//!                           8) TX509 Extension Tests 08 - All possible capabilities except TCB.

//!                           9) TX509 Extension Tests 09 - All possible capabilities except TCB.

//!                           10) TX509 Extension Tests 10 - Test error handling of zero length integer fields.

//!                           11) TX509 Extension Tests 11 - Incorrect data type associated with an OID.

//!                           12) TX509 Extension Tests 12 - Symbian Signed Refernce - 1

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-001

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-002

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-003

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-004

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-005

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-006

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-007

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-008

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-009

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-010

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-011

RUN_TEST_STEP                 -1    CTestHandler        Extension              tx509_dev_certs.ini   SEC-CERTMAN-TX509_DEV_CERTS-0001-012

END_TESTCASE                  SEC-CERTMAN-TX509_DEV_CERTS-0001





