// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// This file provides instructions on how to do manual integration testing for 
// the feature manager component 
// 
// @file
//

//! @SYMTestSuiteName SYSLIB-TEF-EFM-INTEGRATION
//! @SYMScriptTestEnvironment TEF
//! @internalComponent
//! @test

Instructions for SYSLIB-EFM-CIT-3682 (Feature data generator and ROM builder testing: normal use test case)
Please refer to the SGL.TS0017.268 Feature Manager Testability How To.doc document for the instructions on this test case.
The detailed specification of this test case can be found in tef_efm_singleromsection.script

Instructions for SYSLIB-EFM-CIT-3683 (Composite  ROM test)
Please refer to the SGL.TS0017.268 Feature Manager Testability How To.doc document for the instructions on this test case.The detailed specification of this test case can be found in tef_efm_multipleromsection.script

Instructions for SYSLIB-EFM-CIT-4032 (header generator acceptance testing)
Please refer to the SGL.TS0017.268 Feature Manager Testability How To.doc document for the instructions on this test case.The detailed specification of this test case can be found in tef_efm_multipleromsection.script

Instructions for SYSLIB-EFM-CIT-4031 (Emulator tool acceptance testing)
Please refer to the SGL.TS0017.268 Feature Manager Testability How To.doc document for the instructions on this test case.The detailed specification of this test case can be found in tef_efm_multipleromsection.script
