/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/


/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_example_SomeObject
#define DBUS_GLIB_CLIENT_WRAPPERS_com_example_SomeObject

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_example_SomeObject_method1 (DBusGProxy *proxy, const guint IN_x, const GArray* IN_y, guint* OUT_z, GError **error)

{
  return dbus_g_proxy_call (proxy, "Method1", error, G_TYPE_UINT, IN_x, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_y, G_TYPE_INVALID, G_TYPE_UINT, OUT_z, G_TYPE_INVALID);
}

typedef void (*com_example_SomeObject_method1_reply) (DBusGProxy *proxy, guint OUT_z, GError *error, gpointer userdata);

static void
com_example_SomeObject_method1_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData *)user_data;
  GError *error = NULL;
  guint OUT_z;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_UINT, &OUT_z, G_TYPE_INVALID);
  (*(com_example_SomeObject_method1_reply)data->cb) (proxy, OUT_z, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_example_SomeObject_method1_async (DBusGProxy *proxy, const guint IN_x, const GArray* IN_y, com_example_SomeObject_method1_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Method1", com_example_SomeObject_method1_async_callback, stuff, g_free, G_TYPE_UINT, IN_x, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_y, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_example_SomeObject */

G_END_DECLS
