// Copyright (c) 1998-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// DBMS version numbers
// 
//

#ifndef __D32VER_H__
#define __D32VER_H__

#ifndef __E32STD_H__
#include <e32std.h>
#endif

/**
@internalComponent
*/
const TInt KDbmsMajorVersion=2;
const TInt KDbmsMinorVersion=0;
const TInt KDbmsBuildVersion=1;

#endif
