<G>
<P>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P Alignment=Center>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P SpaceAfter=42>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P KeepTogether>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P Indent=69>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P StartNewPage>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
<P KeepWithNext>
A bit of <C Underline>text<C !Underline> that <C Bold>pretends<C !Bold> to be an entry's title
