/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

#ifndef __TXTETEXT_INTERNAL_H__
#define __TXTETEXT_INTERNAL_H__

#include <e32std.h>
/**
UIDs
@internalComponent
*/
const TUid KPlainTextFieldDataUid = {268435555};
const TUid KEditableTextUid = {268450334};
const TUid KPlainTextCharacterDataUid = {268450341};
const TUid KUidRichText = {271013233};

/**
@internalComponent
*/
const TInt KMaxFieldBufferSize=0x14;

#endif
