/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

#ifndef __TXTRICH_INTERNAL_H__
#define __TXTRICH_INTERNAL_H__

#include <e32std.h>

/**
UIDs
@internalComponent 
*/
const TUid KRichTextStyleDataUid = { 268450335 };
const TUid KRichTextMarkupDataUid = { 268435558 };

#endif
