/*
* Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/


#ifndef __TXTUIDS_H__
#define __TXTUIDS_H__

#include <e32std.h>

/**
@internalComponent 
*/
const TUid KUidTextFieldStream = { 268435778 };
const TUid KUidTextMarkupStream = { 268435779 };
const TUid KUidParagraphStyleStream = { 268450339 };
const TUid KUidEditableTextStream = { 268450340 };

#endif
