
Typeface Symbol
    Name "Symbol" Symbol Proportional
    FontBitmaps
        agnsym11
        agnsym16
    EndFontBitmaps
EndTypeface

Typeface Calc
    Name "Calc" Symbol
    FontBitmaps
        calc35
        calc13
        calc18
    EndFontBitmaps
EndTypeface

Typeface Digital
    Name "Digital" Symbol
    FontBitmaps
        digit35
    EndFontBitmaps
EndTypeface

Typeface Calcinv
    Name "Calcinv" Symbol
    FontBitmaps
        calcinv
    EndFontBitmaps
EndTypeface

Typeface Eikon
    Name "Eikon" Symbol
    FontBitmaps
        eiksym15
    EndFontBitmaps
EndTypeface

FontStoreFile
    CollectionUid 268435509
    KPixelAspectRatio 1000
    CopyrightInfo 
        "© Copyright Symbian Software Ltd 2006"
    EndCopyrightInfo
    FontBitmaps
        squashed   
    EndFontBitmaps
    Typefaces
        Symbol
        Calc
        Eikon
        Calcinv
        Digital
    EndTypefaces
EndFontStoreFile
