// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tdb_blr
LOAD_SUITE tdb_blr

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrgid_pos \tstdapis\tdb_blr.ini Section_getgrgid_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrgid_neg \tstdapis\tdb_blr.ini Section_getgrgid_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrnam_pos \tstdapis\tdb_blr.ini Section_getgrnam_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrnam_neg \tstdapis\tdb_blr.ini Section_getgrnam_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrgid_r_pos \tstdapis\tdb_blr.ini Section_getgrgid_r_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrgid_r_neg \tstdapis\tdb_blr.ini Section_getgrgid_r_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrnam_r_pos \tstdapis\tdb_blr.ini Section_getgrnam_r_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getgrnam_r_neg \tstdapis\tdb_blr.ini Section_getgrnam_r_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwuid_pos \tstdapis\tdb_blr.ini Section_getpwuid_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwuid_neg \tstdapis\tdb_blr.ini Section_getpwuid_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwnam_pos \tstdapis\tdb_blr.ini Section_getpwnam_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwnam_neg \tstdapis\tdb_blr.ini Section_getpwnam_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwuid_r_pos \tstdapis\tdb_blr.ini Section_getpwuid_r_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0013

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwuid_r_neg \tstdapis\tdb_blr.ini Section_getpwuid_r_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwnam_r_pos \tstdapis\tdb_blr.ini Section_getpwnam_r_pos
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TESTDBBLR-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTDBBLR-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tdb_blr getpwuid_r_neg \tstdapis\tdb_blr.ini Section_getpwuid_r_neg
END_TESTCASE  		OPENENV-LIBC-CIT-TESTDBBLR-0016

