// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tclock
LOAD_SUITE tclock

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0001
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testgetclockid1 
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0001

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0002
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testgetclockid2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0002

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0003
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testgetclockid3 
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0003

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0004
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testgetclockid4 
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0004

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0005
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testgetclockid5 
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0005

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0006
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution1 
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0006

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0007
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution2  \tstdapis\tclock.ini Sectionclock_res1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0007

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0008
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution2  \tstdapis\tclock.ini Sectionclock_res2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0008

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0009
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution2  \tstdapis\tclock.ini Sectionclock_res3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0009

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0010
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution3  \tstdapis\tclock.ini Sectionclock_res4
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0010

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0011
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution3  \tstdapis\tclock.ini Sectionclock_res5
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0011

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0012
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockresolution3  \tstdapis\tclock.ini Sectionclock_res6
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0012

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0013
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0013

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0014
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime2 \tstdapis\tclock.ini Sectionclock_gettime1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0014

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0015
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime2 \tstdapis\tclock.ini Sectionclock_gettime2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0015

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0016
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime2 \tstdapis\tclock.ini Sectionclock_gettime3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0016

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0017
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime3 \tstdapis\tclock.ini Sectionclock_gettime4
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0017

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0018
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0018
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclockgettime3 \tstdapis\tclock.ini Sectionclock_gettime5
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0018

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0019
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0019
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime1 \tstdapis\tclock.ini Sectionclock_settime1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0019

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0020
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0020
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime1 \tstdapis\tclock.ini Sectionclock_settime2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0020

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0021
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0021
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime2 \tstdapis\tclock.ini Sectionclock_settime3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0021

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0022
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0022
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime2 \tstdapis\tclock.ini Sectionclock_settime4
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0022

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0023
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0023
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime2 \tstdapis\tclock.ini Sectionclock_settime5
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0023

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0024
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0024
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime3 \tstdapis\tclock.ini Sectionclock_settime6
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0024

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0025
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0025
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime3 \tstdapis\tclock.ini Sectionclock_settime7
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0025

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0026
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0026
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime3 \tstdapis\tclock.ini Sectionclock_settime8
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0026

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0027
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0027
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime3 \tstdapis\tclock.ini Sectionclock_settime9
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0027

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0028
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0028
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocksettime3 \tstdapis\tclock.ini Sectionclock_settime10
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0028

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0029
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0029
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep1 \tstdapis\tclock.ini Sectionclock_nanosleep1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0029

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0030
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0030
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep1 \tstdapis\tclock.ini Sectionclock_nanosleep2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0030

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0031
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0031
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep1 \tstdapis\tclock.ini Sectionclock_nanosleep3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0031

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0032
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0032
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep2 \tstdapis\tclock.ini Sectionclock_nanosleep1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0032

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0033
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0033
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep2 \tstdapis\tclock.ini Sectionclock_nanosleep2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0033

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0034
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0034
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep2 \tstdapis\tclock.ini Sectionclock_nanosleep3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0034

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0035
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0035
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep3 \tstdapis\tclock.ini Sectionclock_nanosleep4
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0035

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0036
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0036
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep3 \tstdapis\tclock.ini Sectionclock_nanosleep5
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0036

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0037
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0037
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep4 \tstdapis\tclock.ini Sectioninvalidclockid1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0037

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0038
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0038
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep4 \tstdapis\tclock.ini Sectioninvalidclockid2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0038

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0039
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0039
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep4 \tstdapis\tclock.ini Sectioninvalidclockid3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0039

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0040
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0040
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep4 \tstdapis\tclock.ini Sectioninvalidclockid4
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0040

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0041
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0041
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tclock  Testclocknanosleep5
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0041

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0042
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0042
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep6 \tstdapis\tclock.ini Sectionclock_nanosleep1
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0042

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0043
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0043
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep6 \tstdapis\tclock.ini Sectionclock_nanosleep2
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0043

START_TESTCASE  	OPENENV-LIBRT-CIT-TESTCLOCK-0044
//! @SYMTestCaseID 	OPENENV-LIBRT-CIT-TESTCLOCK-0044
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 10 tclock  Testclocknanosleep6 \tstdapis\tclock.ini Sectionclock_nanosleep3
END_TESTCASE  		OPENENV-LIBRT-CIT-TESTCLOCK-0044

