// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tinet
LOAD_SUITE tinet

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_addr_with_valid_input \tstdapis\tinet.ini Section_Inet_addr_with_valid_input
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_addr_with_invalid_input \tstdapis\tinet.ini Section_Inet_addr_with_invalid_input
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_ntoaTest \tstdapis\tinet.ini Section_Inet_ntoaTest
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=-2 5 tinet  Inet_ptonTest \tstdapis\tinet.ini Section_Inet_ptonTest_1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=-2 5 tinet  Inet_ptonTest \tstdapis\tinet.ini Section_Inet_ptonTest_2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_ptonTest \tstdapis\tinet.ini Section_Inet_ptonTest_3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_ptonTest \tstdapis\tinet.ini Section_Inet_ptonTest_4
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tinet  Inet_ntopTest \tstdapis\tinet.ini Section_Inet_ntopTest_1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TESTINET-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTINET-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=-2 5 tinet  Inet_ntopTest \tstdapis\tinet.ini Section_Inet_ntopTest_2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTINET-0009




