// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all tmkfifo
LOAD_SUITE tmkfifo

CONSECUTIVE

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0001
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest1 \tstdapis\tmkfifo.ini Section_IntgTest1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0001

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0002
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest2 \tstdapis\tmkfifo.ini Section_IntgTest2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0002

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0003
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNULL \tstdapis\tmkfifo.ini Section_FifoCreateNULL
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0003

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0004
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateInSystemDir
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0004

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0005
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0005
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNameTooLong
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0005

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0006
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0006
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest3 \tstdapis\tmkfifo.ini Section_IntgTest3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0006

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0007
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0007
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNonExistantDir
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0007

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0008
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0008
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0008

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0009
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0009
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest5 \tstdapis\tmkfifo.ini Section_IntgTest5
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0009

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0010
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0010
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_2
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0010

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0011
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0011
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest6 \tstdapis\tmkfifo.ini Section_IntgTest6
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0011

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0012
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0012
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest4 \tstdapis\tmkfifo.ini Section_IntgTest4_3
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0012

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0013
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0013
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  IntgTest7 \tstdapis\tmkfifo.ini Section_IntgTest7
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0013

//START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0014
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0014
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  TMkfifoReaderWriter \tstdapis\tmkfifo.ini Section_TMkfifoReaderWriter
//END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0014

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0015
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0015
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  TMkfifoReaderWriter1 \tstdapis\tmkfifo.ini Section_TMkfifoReaderWriter1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0015

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0016
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0016
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreateNULL1
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0016

START_TESTCASE  	OPENENV-LIBC-CIT-TESTMKFIFO-0017
//! @SYMTestCaseID 	OPENENV-LIBC-CIT-TESTMKFIFO-0017
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=0 5 tmkfifo  FifoCreate_invalid
END_TESTCASE  		OPENENV-LIBC-CIT-TESTMKFIFO-0017
