// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

CONSECUTIVE

START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0001
PRINT --------  Testing utime,Capability set to None
RUN_PROGRAM -1 setcap.exe tutimecap.exe 000000  tutime_cap1.exe
LOAD_SUITE tutime_cap1
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0001
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP   !Result=13 tutime_cap1 utimesys
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0001




START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0002
PRINT --------  Testing utime,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tutimecap.exe 000800  tutime_cap2.exe
LOAD_SUITE tutime_cap2
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0002
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tutime_cap2 utimesys
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0002



START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0003
PRINT --------  Testing utime,Capability set to None
RUN_PROGRAM -1 setcap.exe tutimecap.exe 000000  tutime_cap3.exe
LOAD_SUITE tutime_cap3
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0003
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tutime_cap3 utimeprivate
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0003



START_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0004
PRINT --------  Testing utime,Capability set to AllFiles
RUN_PROGRAM -1 setcap.exe tutimecap.exe 000800  tutime_cap4.exe
LOAD_SUITE tutime_cap4
//! @SYMTestCaseID OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0004
//! @SYMTestStatus 	3.Released
RUN_TEST_STEP !Result=13 tutime_cap4 utimeprivate
END_TESTCASE  OPENENV-LIBC-CIT-TESTCAPUTIME-OE-0004




