/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/


/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_example_DBusGlibObject2
#define DBUS_GLIB_CLIENT_WRAPPERS_com_example_DBusGlibObject2

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_example_DBusGlibObject2_send_message0 (DBusGProxy *proxy, const char * IN_in_str, gint* OUT_ret, GError **error)

{
  return dbus_g_proxy_call (proxy, "Send_message0", error, G_TYPE_STRING, IN_in_str, G_TYPE_INVALID, G_TYPE_INT, OUT_ret, G_TYPE_INVALID);
}

typedef void (*com_example_DBusGlibObject2_send_message0_reply) (DBusGProxy *proxy, gint OUT_ret, GError *error, gpointer userdata);

static void
com_example_DBusGlibObject2_send_message0_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_ret;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_ret, G_TYPE_INVALID);
  (*(com_example_DBusGlibObject2_send_message0_reply)data->cb) (proxy, OUT_ret, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_example_DBusGlibObject2_send_message0_async (DBusGProxy *proxy, const char * IN_in_str, com_example_DBusGlibObject2_send_message0_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Send_message0", com_example_DBusGlibObject2_send_message0_async_callback, stuff, g_free, G_TYPE_STRING, IN_in_str, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_example_DBusGlibObject2 */

G_END_DECLS
